from sqlalchemy import (
    Column,
    String,
    ForeignKey,
    Enum as SqlEnum,
    Boolean,
    Integer,
    Index,
    Text,
    asc,
    text,
)
from sqlalchemy.dialects.mysql import DATETIME
from sqlalchemy.orm import relationship
from enum import Enum
from uuid import uuid4

from common.database import Base, uuid_generator


class SenderRole(Enum):
    SYSTEM = "system"
    USER = "user"
    AGENT = "agent"
    TOOL = "tool"

    # Role for special messages generated by the system to represent actions taken by tools
    ANALYSIS_PROGRESS = "analysis_progress"
    AGENT_FUNCTION_CALL = "agent_function_call"

    # Role for error messages
    ERROR = "error"


class ChatSession(Base):
    __tablename__ = "chat_sessions"

    id = Column(String(64), primary_key=True, default=uuid_generator)
    user_id = Column(
        String(64), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )

    connection_id = Column(
        String(64),
        ForeignKey("connections.platform_connection_id", ondelete="CASCADE"),
        nullable=False,
    )

    project_key = Column(String(32), nullable=False, index=True)
    # If not null, the chat session is associated with a specific story
    story_key = Column(String(32), nullable=True, index=True)
    created_at = Column(
        DATETIME(fsp=2), server_default=text("CURRENT_TIMESTAMP(2)"), nullable=False
    )

    # user = relationship("User", back_populates="sessions")
    messages = relationship(
        "Message",
        back_populates="session",
        cascade="all, delete-orphan",
        lazy="joined",
        order_by=lambda: asc(Message.created_at),
    )
    change_proposals = relationship(
        "StoryChangeProposal",
        back_populates="session",
        cascade="all, delete-orphan",
        lazy="joined",
    )

    user = relationship("User", back_populates="chat_sessions")

    # Index project key and story key for faster retrieval
    __table_args__ = (
        Index("ix_chat_sessions_project_story", "project_key", "story_key"),
    )


class Message(Base):
    __tablename__ = "messages"

    id = Column(String(64), primary_key=True, default=uuid_generator)
    session_id = Column(
        String(64),
        ForeignKey("chat_sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    role = Column(SqlEnum(SenderRole), nullable=False)
    content = Column(Text, nullable=False)

    # Non-null if role is ANALYSIS_PROGRESS
    analysis_id = Column(String(64), ForeignKey("analyses.id"), nullable=True)

    created_at = Column(
        DATETIME(fsp=2),
        server_default=text("CURRENT_TIMESTAMP(2)"),
        nullable=False,
        index=True,
    )

    analysis = relationship("Analysis", lazy="joined", uselist=False)

    session = relationship("ChatSession", back_populates="messages")

    __table_args__ = (Index("ix_messages_session_created", "session_id", "created_at"),)


class WorkItemVersion(Base):
    __tablename__ = "work_item_versions"

    id = Column(String(64), primary_key=True, default=uuid_generator)
    story_key = Column(String(32), nullable=False, unique=True, index=True)
    version = Column(Integer, nullable=False, default=0)
    summary = Column(Text, nullable=True)
    description = Column(Text, nullable=True)

    created_at = Column(
        DATETIME(fsp=2), server_default=text("CURRENT_TIMESTAMP(2)"), nullable=False
    )


class ProposalType(Enum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"

    UNKNOWN = "UNKNOWN"

    @classmethod
    def _missing_(cls, value):
        return cls.UNKNOWN


class StoryChangeProposal(Base):
    __tablename__ = "story_change_proposals"

    id = Column(String(64), primary_key=True, default=uuid_generator)
    session_id = Column(
        String(64),
        ForeignKey("chat_sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    project_key = Column(String(32), nullable=False, index=True)
    type = Column(SqlEnum(ProposalType), nullable=False)

    accepted = Column(
        Boolean, nullable=True
    )  # None = pending, True = accepted, False = rejected

    created_at = Column(
        DATETIME(fsp=2), server_default=text("CURRENT_TIMESTAMP(2)"), nullable=False
    )

    session = relationship("ChatSession", back_populates="change_proposals")
    contents = relationship(
        "StoryChangeContent",
        back_populates="proposal",
        cascade="all, delete-orphan",
        lazy="joined",
    )


class StoryChangeContent(Base):
    __tablename__ = "story_change_contents"

    id = Column(String(64), primary_key=True, default=uuid_generator)
    proposal_id = Column(
        String(64),
        ForeignKey("story_change_proposals.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    story_key = Column(
        String(32), nullable=True, index=True, default=None
    )  # The key of the User Story (Jira Issue). None for CREATE proposals
    summary = Column(Text, nullable=True)
    description = Column(Text, nullable=True)

    rollback_version = Column(
        Integer, nullable=True
    )  # Version to rollback to, if accepted

    proposal = relationship("StoryChangeProposal", back_populates="contents")
