from typing import List, Literal, Optional
from pydantic import BaseModel, Field
from common.agents.input_schemas import ContextInput


class ACGeneratorInput(BaseModel):
    """Schema for the input to the AC generator."""

    summary: str = Field(description="Title of the User Story.")
    description: str = Field(description="Description of the User Story.")
    existing_ac: Optional[str] = Field(
        None, description="Existing Acceptance Criteria to be updated or refined."
    )
    user_feedback: Optional[str] = Field(
        None, description="Feedback from the user regarding the existing AC."
    )
    context_input: Optional[ContextInput] = Field(
        None, description="Optional contextual information."
    )


class ACGeneratorOutput(BaseModel):
    """Schema for the output of the AC generator."""

    gherkin_ac: str = Field(
        description="The generated or refined Acceptance Criteria in Gherkin format."
    )
    reasoning: Optional[str] = Field(
        None, description="Explanation of the generated ACs or changes made."
    )


class ACReview(BaseModel):
    """Schema for the review of the generated AC."""

    status: Literal["APPROVE", "REWRITE"] = Field(
        description="The decision status for the AC."
    )
    feedback: Optional[str] = Field(
        None,
        description="Specific instructions on what to change for REWRITE status.",
    )
    reasoning: Optional[str] = Field(None, description="Explanation of the decision.")


class ACReviewerInput(BaseModel):
    """Schema for the input to the AC reviewer."""

    user_story_title: str = Field(description="Title of the User Story.")
    user_story_description: str = Field(description="Description of the User Story.")
    generated_ac: str = Field(description="The AC generated by the generator.")
    context_input: Optional[ContextInput] = Field(
        None, description="Optional contextual information."
    )


class ACReviewerOutput(BaseModel):
    """Schema for the output of the AC reviewer."""

    review: ACReview = Field(description="The review result.")


class ACRewriterInput(ACGeneratorInput):
    """Schema for the input to the AC rewriter."""

    current_ac: str = Field(description="The current version of the AC.")
    reviewer_feedback: str = Field(
        description="Feedback from the reviewer that needs to be addressed."
    )
