from typing import List, Literal, Optional
from pydantic import BaseModel, Field

from app.analysis.agents.schemas import WorkItemMinimal, DefectInput
from common.agents.input_schemas import ContextInput


class ProposalContent(BaseModel):
    """Schema for individual proposal content within a proposal, detailing the action to be taken on a User Story."""

    type: Literal["CREATE", "UPDATE", "DELETE"] = Field(
        description="The type of action for the proposal content.",
    )
    story_key: Optional[str] = Field(
        description="The story key for UPDATE or DELETE actions. Null for CREATE actions.",
    )
    summary: Optional[str] = Field(
        description="A brief summary of the User Story. Only valid for CREATE or UPDATE actions.",
    )
    description: Optional[str] = Field(
        description="A detailed description of the User Story. Only valid for CREATE or UPDATE actions. ",
    )
    explanation: Optional[str] = Field(
        description="An explanation of the rationale behind the proposed action.",
    )


class Proposal(BaseModel):
    """Schema for a proposal to improve User Stories and address defects."""

    target_defect_ids: List[str] = Field(
        description="List of defect IDs that this proposal aims to address.",
    )
    contents: List[ProposalContent] = Field(
        description="List of proposal contents detailing the actions to be taken.",
    )


class ProposalInput(BaseModel):
    """Schema for the input to the proposal generator."""

    user_stories: List[WorkItemMinimal] = Field(
        description="List of User Stories relevant to the given defects",
    )
    defects: List[DefectInput] = Field(
        description="List of identified defects that need to be addressed.",
    )
    context_input: Optional[ContextInput] = Field(
        None,
        description="Optional contextual information to aid in proposal generation.",
    )


class ProposalOutput(BaseModel):
    """Schema for the output of the proposal generator."""

    proposals: List[Proposal] = Field(
        description="List of generated proposals to solve all the defects.",
    )


class ProposalReview(BaseModel):
    """Schema for the review of a single proposal by the impact analyzer."""

    proposal_index: int = Field(
        description="Index of the proposal being reviewed (0-based).",
    )
    status: Literal["APPROVE", "REWRITE", "REJECT"] = Field(
        description="The decision status for this proposal.",
    )
    feedback: Optional[str] = Field(
        None,
        description="Specific instructions on what to change for REWRITE or REJECT status.",
    )
    reasoning: Optional[str] = Field(
        None,
        description="Explanation of the decision, especially for REJECT status.",
    )


class ImpactAnalyzerInput(BaseModel):
    """Schema for the input to the impact analyzer."""

    user_stories: List[WorkItemMinimal] = Field(
        description="List of original User Stories.",
    )
    defects: List[DefectInput] = Field(
        description="List of identified defects.",
    )
    proposals: List[Proposal] = Field(
        description="List of proposals generated by the drafter.",
    )
    context_input: Optional[ContextInput] = Field(
        None,
        description="Optional contextual information.",
    )


class ImpactAnalyzerOutput(BaseModel):
    """Schema for the output of the impact analyzer."""

    reviews: List[ProposalReview] = Field(
        description="List of reviews for each proposal.",
    )


class RewriterInput(BaseModel):
    """Schema for the input to the proposal rewriter."""

    user_stories: List[WorkItemMinimal] = Field(
        description="List of original User Stories.",
    )
    defects: List[DefectInput] = Field(
        description="List of identified defects.",
    )
    original_proposals: List[Proposal] = Field(
        description="List of original proposals that need rewriting.",
    )
    feedback: List[ProposalReview] = Field(
        description="List of feedback from the impact analyzer for proposals that need rewriting.",
    )
    context_input: Optional[ContextInput] = Field(
        None,
        description="Optional contextual information.",
    )


class ProposalReview(BaseModel):
    """Schema for the review of a single proposal by the impact analyzer."""

    proposal_index: int = Field(
        description="Index of the proposal being reviewed (0-based).",
    )
    status: Literal["APPROVE", "REWRITE", "REJECT"] = Field(
        description="The decision status for this proposal.",
    )
    feedback: Optional[str] = Field(
        None,
        description="Specific instructions on what to change for REWRITE or REJECT status.",
    )
    reasoning: Optional[str] = Field(
        None,
        description="Explanation of the decision, especially for REJECT status.",
    )


class ImpactAnalyzerInput(BaseModel):
    """Schema for the input to the impact analyzer."""

    user_stories: List[WorkItemMinimal] = Field(
        description="List of original User Stories.",
    )
    defects: List[DefectInput] = Field(
        description="List of identified defects.",
    )
    proposals: List[Proposal] = Field(
        description="List of proposals generated by the drafter.",
    )
    context_input: Optional[ContextInput] = Field(
        None,
        description="Optional contextual information.",
    )


class ImpactAnalyzerOutput(BaseModel):
    """Schema for the output of the impact analyzer."""

    reviews: List[ProposalReview] = Field(
        description="List of reviews for each proposal.",
    )


class RewriterInput(BaseModel):
    """Schema for the input to the proposal rewriter."""

    user_stories: List[WorkItemMinimal] = Field(
        description="List of original User Stories.",
    )
    defects: List[DefectInput] = Field(
        description="List of identified defects.",
    )
    original_proposals: List[Proposal] = Field(
        description="List of original proposals that need rewriting.",
    )
    feedback: List[ProposalReview] = Field(
        description="List of feedback from the impact analyzer for proposals that need rewriting.",
    )
    context_input: Optional[ContextInput] = Field(
        None,
        description="Optional contextual information.",
    )
