from sqlalchemy import (
    Column,
    String,
    ForeignKey,
    Enum as SqlEnum,
    Index,
    Text,
    text,
    DateTime,
)
from sqlalchemy.orm import relationship
from enum import Enum

from common.database import Base, uuid_generator, utcnow


class SenderRole(Enum):
    SYSTEM = "system"
    USER = "user"
    AGENT = "agent"
    TOOL = "tool"

    # Role for special messages generated by the system to represent actions taken by tools
    ANALYSIS_PROGRESS = "analysis_progress"
    AGENT_FUNCTION_CALL = "agent_function_call"

    # Role for error messages
    ERROR = "error"


class ChatSession(Base):
    __tablename__ = "chat_sessions"

    id = Column(String(64), primary_key=True, default=uuid_generator)

    key = Column(String(64), nullable=False, index=True)

    connection_id = Column(
        String(64),
        ForeignKey("connections.platform_connection_id", ondelete="CASCADE"),
        nullable=False,
    )

    project_key = Column(String(32), nullable=False, index=True)
    # If not null, the chat session is associated with a specific story
    story_key = Column(String(32), nullable=True, index=True)
    created_at = Column(DateTime(timezone=True), default=utcnow, nullable=False)

    # user = relationship("User", back_populates="sessions")
    messages = relationship(
        "Message",
        back_populates="session",
        cascade="all, delete-orphan",
    )
    proposals = relationship(
        "Proposal",
        back_populates="chat_session",
        cascade="all, delete-orphan",
    )

    # Index project key and story key for faster retrieval
    __table_args__ = (
        Index("ix_chat_sessions_project_story", "project_key", "story_key"),
    )


class Message(Base):
    __tablename__ = "messages"

    id = Column(String(64), primary_key=True, default=uuid_generator)
    session_id = Column(
        String(64),
        ForeignKey("chat_sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    role = Column(SqlEnum(SenderRole), nullable=False)
    content = Column(Text, nullable=False)

    created_at = Column(
        DateTime(timezone=True),
        default=utcnow,
        nullable=False,
        index=True,
    )

    session = relationship("ChatSession", back_populates="messages")

    __table_args__ = (
        Index("idx_messages_session_created", "session_id", "created_at"),
    )
